l_english:
 is_your_child_desc:0 "Is Your Child"
 is_your_close_family_desc:0 "Is Your Close Family"
 is_your_house_desc:0 "Is of Your House"
 landed_spouse_desc:0 "Has a Landed Spouse"
 landed_heir_desc:0 "Has a Landed Heir"
 has_many_good_relations_desc:0 "Has Many Friends"
 has_many_bad_relations_desc:0 "Is Beset by Rivals"
 part_of_feud_desc:0 "Part of a Feud"
 high_diplomacy_desc:0 "Has High Diplomacy"
 high_martial_desc:0 "Has High Martial"
 high_stewardship_desc:0 "Has High Stewardship"
 high_intrigue_desc:0 "Has High Intrigue"
 high_learning_desc:0 "Has High Learning"
 high_prowess_desc:0 "Has High Prowess"
 high_education_desc:0 "Is Highly Educated"
 more_beautiful_desc:0 "Is More Beautiful than Heir"
 more_smart_desc:0 "Is Smarter than Heir"
 more_fit_desc:0 "Is Fitter than Heir"
 more_strong_desc:0 "Is Stronger than Heir"
 more_skillful_desc:0 "Is More Skillful than Heir"
 has_nickname_desc:0 "Has a Nickname"
 more_famous_desc:0 "More Famous than Heir"
 second_in_line_desc:0 "Second in Line for Inheritance"
 higher_title_desc:0 "Holds a Higher Title"
 new_liege_desc:0 "Would be Under a New Liege"
 new_top_liege_desc:0 "Would be Under a New Top Liege"
 tall_claims_desc:0 "Holds Important Claims"
 pressed_claims_desc:0 "Holds Pressed Claims"
 unpressed_claims_desc:0 "Holds Unpressed Claims"
 inheritance_line_desc:0 "In Line for Inheritance"
 has_interesting_story_desc:0 "Has an Interesting Story"
 child_of_destiny_desc:0 "Is a Child of Destiny"
 virtues_interesting_desc:0 "Has Virtuous Traits"
 tourney_xp_desc:0 "Experienced [GetTrait('tourney_participant').GetName( GetNullCharacter )]"
 reveler_xp_desc:0 "Experienced [GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
 mystic_xp_desc:0 "Experience as a [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
 hunter_xp_desc:0 "Experienced [GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
 blademaster_xp_desc:0 "Experienced [GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
 traveler_xp_desc:0 "Experienced [GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
 physician_xp_desc:0 "Experienced [GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
 herbalist_xp_desc:0 "Experienced [GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
 loyal_interesting_desc:0 "Is [GetTrait('loyal').GetName( GetNullCharacter )]"
 disloyal_interesting_desc:0 "Is [GetTrait('disloyal').GetName( GetNullCharacter )]"
 faith_warrior_interesting_desc:0 "Is a [GetTrait('faith_warrior').GetName( GetNullCharacter )]"
 blood_of_prophet_interesting_desc:0 "Has the [GetTrait('blood_of_prophet').GetName( GetNullCharacter )]"
 varangian_interesting_desc:0 "Is a [GetTrait('varangian').GetName( GetNullCharacter )]"
 poet_interesting_desc:0 "Is a [GetTrait('poet').GetName( GetNullCharacter )]"
 peasant_leader_interesting_desc:0 "Is a [GetTrait('peasant_leader').GetName( GetNullCharacter )]"
 populist_leader_interesting_desc:0 "Is a [GetTrait('populist_leader').GetName( GetNullCharacter )]"
 berserker_interesting_desc:0 "Is a [GetTrait('berserker').GetName( GetNullCharacter )]"
 born_in_the_purple_interesting_desc:0 "Is [GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
 scaly_interesting_desc:0 "Has [GetTrait('scaly').GetName( GetNullCharacter )] Skin"
 albino_interesting_desc:0 "Is an [GetTrait('albino').GetName( GetNullCharacter )]"
 dwarf_interesting_desc:0 "Is a [GetTrait('dwarf').GetName( GetNullCharacter )]"
 giant_interesting_desc:0 "Is a [GetTrait('giant').GetName( GetNullCharacter )]"
 devoted_interesting_desc:0 "Is a [GetTrait('devoted').GetName( GetNullCharacter )]"
 pure_blooded_interesting_desc:0 "Is [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc:0 "Is a [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 disinherited_interesting_desc:0 "Is [GetTrait('disinherited').GetName( GetNullCharacter )]"
 blind_interesting_desc:0 "Is [GetTrait('blind').GetName( GetNullCharacter )]"
 is_diarch_interesting_desc:0 "Is a Diarch"
 ruler_in_foreign_lands_interesting_desc:0 "Is a Ruler in Foreign Lands"
 valiant_knight_interesting_desc:0 "Is a Valiant Knight"
 sinful_bastard_interesting_desc:0 "Is a Sinful [GetTrait('bastard').GetName( GetNullCharacter )]"
 adventurer_interesting_desc:0 "Is an Adventurer"
 liege_crusader_king_liege_lineage_interesting_desc:0 "Liege of [GetTrait('crusader_king').GetName( GetNullCharacter )] Lineage"
 holy_site_steward_interesting_desc:0 "Capital is a Holy Site"
 has_a_legend_interesting_desc:0 "Has a Legend"
 weak_hook_liege_interesting_desc:0 "Has Weak Hook on Liege"
 strong_hook_liege_interesting_desc:0 "Has Strong Hook on Liege"
 beloved_by_pope_interesting_desc:0 "Beloved by the Pope"
 head_of_faith_interesting_desc:0 "Is a Head of Faith"
 stronger_than_liege_interesting_desc:0 "Stronger than Liege"
 small_king_interesting_desc:0 "Is a Small Kingdom Ruler"
 can_feudalize_interesting_desc:0 "Can Feudalize"
 multiduke_interesting_desc:0 "Holds many Duchies"
 legitimacy_interesting_desc:0 "Extremely Legitimate Ruler"
 non_dominant_gender_ambitious_char_interesting_desc:0 "Is an Ambitious Non-Dominant Gender Character"
 non_dominant_gender_ruler_interesting_desc:0 "Is a Non-Dominant Gender Ruler"
 treacherous_schemer_interesting_desc:0 "Is a Treacherous Schemer"
 kind_hearted_diplomat_interesting_desc:0 "Is a Kind-Hearted Diplomat"
 different_faith_interesting_desc:0 "Of Different Faith"
 greedy_steward_interesting_desc:0 "Is a Greedy Steward"
 brazen_commander_interesting_desc:0 "Is a Brazen Commander"
 pious_theologian_interesting_desc:0 "Is a Pious Theologian"
 salacious_seducer_interesting_desc:0 "Is a Salacious Seducer"
 high_skills_desc:0 "Skills are Very High"
 killed_a_lot_interesting_desc:0 "Killed Over 10 People"
 has_both_good_and_bad_genetics_desc:0 "Has Both Good and Bad Genetic Traits"
 good_genetics_desc:0 "Good Genetic Traits"
 bad_genetics_desc:0 "Bad Genetic Traits"
 holds_rome_interesting_desc:0 "Holds the [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc:0 "Holds the [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc:0 "Holds the [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc:0 "Holds the [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc:0 "Holds the [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc:0 "Controls Special Buildings"
 has_historical_artifacts_interesting_desc:0 "Owns Unique Historical Artifacts"
 underrepresented_faith_interesting_desc:0 "Is of an Underrepresented Faith"
 underrepresented_culture_interesting_desc:0 "Is of an Underrepresented Culture"
 outside_realm_desc:0 "Independent Ruler"
 knows_many_secrets_interesting_desc:0 "Knows Many Secrets"
 has_secrets_interesting_desc:0 "Has Secrets"
 extremely_wealthy_interesting_desc:0 "Very Wealthy"
 landless_heir_uninteresting_desc:0 "Unlanded Title Heir"
 three_virtues_desc:0 "Has Three Virtues"
 three_sins_desc:0 "Has Three Sins"
 skills_difficulty:0 "From Skills"
 legitimacy_difficulty:0 "From Legitimacy"
 virtuous_traits_difficulty:0 "Has Virtuous Traits"
 physique_good_3_difficulty:0 "Is [GetTrait('physique_good_3').GetName( GetNullCharacter )]"
 physique_good_2_difficulty:0 "Is [GetTrait('physique_good_2').GetName( GetNullCharacter )]"
 physique_good_1_difficulty:0 "Is [GetTrait('physique_good_1').GetName( GetNullCharacter )]"
 intellect_good_3_difficulty:0 "Is [GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
 intellect_good_2_difficulty:0 "Is [GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
 intellect_good_1_difficulty:0 "Is [GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
 beauty_good_3_difficulty:0 "Is [GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
 beauty_good_2_difficulty:0 "Is [GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
 beauty_good_1_difficulty:0 "Is [GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
 shrewd_difficulty:0 "Is [GetTrait('shrewd').GetName( GetNullCharacter )]"
 strong_difficulty:0 "Is [GetTrait('strong').GetName( GetNullCharacter )]"
 sinful_traits_difficulty:0 "Has Sinful Traits"
 incapable_difficulty:0 "Is [GetTrait('incapable').GetName( GetNullCharacter )]"
 leper_difficulty:0 "Is a [GetTrait('leper').GetName( GetNullCharacter )]"
 maimed_difficulty:0 "Is [GetTrait('maimed').GetName( GetNullCharacter )]"
 inbred_difficulty:0 "Is [GetTrait('inbred').GetName( GetNullCharacter )]"
 severely_wounded_difficulty:0 "Is Severely Wounded"
 disinherited_difficulty:0 "Is [GetTrait('disinherited').GetName( GetNullCharacter )]"
 sickly_difficulty:0 "Is [GetTrait('sickly').GetName( GetNullCharacter )]"
 poxed_difficulty:0 "Has the [GetTrait('great_pox').GetName( GetNullCharacter )]"
 blind_difficulty:0 "Is [GetTrait('blind').GetName( GetNullCharacter )]"
 infirm_difficulty:0 "Is [GetTrait('infirm').GetName( GetNullCharacter )]"
 eunuch_difficulty:0 "Is a [GetTrait('eunuch_1').GetName( GetNullCharacter )]"
 lunatic_difficulty:0 "Is a [GetTrait('lunatic').GetName( GetNullCharacter )]"
 murderer_difficulty:0 "Is a [GetTrait('murderer').GetName( GetNullCharacter )]"
 excommunicated_difficulty:0 "Is Excommunicated"
 bleeder_difficulty:0 "Is a [GetTrait('bleeder').GetName( GetNullCharacter )]"
 physique_bad_3_difficulty:0 "Is [GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
 physique_bad_2_difficulty:0 "Is [GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
 physique_bad_1_difficulty:0 "Is [GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
 intellect_bad_3_difficulty:0 "Is [GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
 intellect_bad_2_difficulty:0 "Is [GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
 intellect_bad_1_difficulty:0 "Is [GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
 beauty_bad_3_difficulty:0 "Is [GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
 beauty_bad_2_difficulty:0 "Is [GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
 beauty_bad_1_difficulty:0 "Is [GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
 dull_difficulty:0 "Is [GetTrait('dull').GetName( GetNullCharacter )]"
 weak_difficulty:0 "Is [GetTrait('weak').GetName( GetNullCharacter )]"
 sodomite_difficulty:0 "Is a [GetTrait('sodomite').GetName( GetNullCharacter )]"
 incestuous_difficulty:0 "Is [GetTrait('incestuous').GetName( GetNullCharacter )]"
 fornicator_difficulty:0 "Is a [GetTrait('fornicator').GetName( GetNullCharacter )]"
 adulterer_difficulty:0 "Is an [GetTrait('adulterer').GetName( GetNullCharacter )]"
 cannibal_difficulty:0 "Is a [GetTrait('cannibal').GetName( GetNullCharacter )]"
 witch_difficulty:0 "Is a [GetTrait('witch').GetName( GetNullCharacter )]"
 kinslayer_difficulty:0 "Is a [GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
 flagellant_difficulty:0 "Is a [GetTrait('flagellant').GetName( GetNullCharacter )]"
 improvident_difficulty:0 "Is [GetTrait('improvident').GetName( GetNullCharacter )]"
 profligate_difficulty:0 "Is [GetTrait('profligate').GetName( GetNullCharacter )]"
 disfigured_difficulty:0 "Is [GetTrait('disfigured').GetName( GetNullCharacter )]"
 drunkard_difficulty:0 "Is a [GetTrait('drunkard').GetName( GetNullCharacter )]"
 possessed_difficulty:0 "Is [GetTrait('possessed').GetName( GetNullCharacter )]"
 depressed_difficulty:0 "Is [GetTrait('depressed').GetName( GetNullCharacter )]"
 infertile_difficulty:0 "Is [GetTrait('infertile').GetName( GetNullCharacter )]"
 spindly_difficulty:0 "Is [GetTrait('spindly').GetName( GetNullCharacter )]"
 paranoid_difficulty:0 "Is [GetTrait('paranoid').GetName( GetNullCharacter )]"
 gout_difficulty:0 "Has [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 wheezing_difficulty:0 "Is [GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty:0 "Is [GetTrait('craven').GetName( GetNullCharacter )]"
 shy_difficulty:0 "Is [GetTrait('shy').GetName( GetNullCharacter )]"
 decadent_difficulty:0 "Is [GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty:0 "Is [GetTrait('denounced').GetName( GetNullCharacter )]"
 bastard_difficulty:0 "Is a [GetTrait('bastard').GetName( GetNullCharacter )]"
 weak_heritage_difficulty:0 "Has Weak Heritage"
 comfort_eater_difficulty:0 "Is a [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 inappetetic_difficulty:0 "Is [GetTrait('inappetetic').GetName( GetNullCharacter )]"
 reclusive_difficulty:0 "Is [GetTrait('reclusive').GetName( GetNullCharacter )]"
 irritable_difficulty:0 "Is [GetTrait('irritable').GetName( GetNullCharacter )]"
 rakish_difficulty:0 "Is [GetTrait('rakish').GetName( GetNullCharacter )]"
 hashishiyah_difficulty:0 "Is a [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 celibate_difficulty:0 "Is [GetTrait('celibate').GetName( GetNullCharacter )]"
 lovers_pox_difficulty:0 "Has [GetTrait('lovers_pox').GetName( GetNullCharacter )]"
 wounded_difficulty:0 "Is [GetTrait('wounded_1').GetName( GetNullCharacter )]"
 albino_difficulty:0 "Is an [GetTrait('albino').GetName( GetNullCharacter )]"
 lisping_difficulty:0 "Has a [GetTrait('lisping').GetName( GetNullCharacter )] Impediment"
 stuttering_difficulty:0 "Has a [GetTrait('stuttering').GetName( GetNullCharacter )] Impediment"
 giant_difficulty:0 "Is a [GetTrait('giant').GetName( GetNullCharacter )]"
 scaly_difficulty:0 "Has [GetTrait('scaly').GetName( GetNullCharacter )] Skin"
 clubfooted_difficulty:0 "Is [GetTrait('clubfooted').GetName( GetNullCharacter )]"
 dwarf_difficulty:0 "Is a [GetTrait('dwarf').GetName( GetNullCharacter )]"
 hunchbacked_difficulty:0 "Is [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 lazy_difficulty:0 "Is [GetTrait('lazy').GetName( GetNullCharacter )]"
 gluttonous_difficulty:0 "Is [GetTrait('gluttonous').GetName( GetNullCharacter )]"
 deviant_difficulty:0 "Is a [GetTrait('deviant').GetName( GetNullCharacter )]"
 at_war_difficulty:0 "At War"
 losing_war_difficulty:0 "Losing Wars"
 faction_difficulty:0 "Targeted by Powerful Factions"
 powerful_neighbors_difficulty:0 "Powerful Neighboring Rulers"
 military_difficulty:0 "Military Strength"
 rivals_difficulty:0 "Has Rivals"
 primary_heir_wrong_dynasty_difficulty:0 "Primary Heir from Wrong Dynasty"
 children_wrong_dynasty_difficulty:0 "Children are of the Wrong Dynasty"
 hostile_faith_liege_difficulty:0 "Liege of Hostile Faith"
 nonpreferred_gender_difficulty:0 "Non-Preferred Gender in Faith"
 wrong_lineality_difficulty:0 "Wrong Lineality in Marriage"
 stress_level_difficulty:0 "High Stress Level"
 gold_difficulty:0 "Excessive Wealth"
 debt_level_difficulty:0 "High Debt Level"
 is_ill_difficulty:0 "Suffering from Debilitating Illness"
 imprisoned_difficulty:0 "Imprisoned"
 elder_difficulty:0 "Advanced Age"
 poor_health_difficulty:0 "Poor Health"
 is_a_vassal_difficulty:0 "Is a Vassal"
 non_adult_difficulty:0 "Child"
 weak_domain_difficulty:0 "Weak Domain"
 unlanded_difficulty:0 "Holds no Titles"
 character_difficulty_text:0 "Difficulty: [Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header:0 "Difficulty Breakdown"
 choose_destiny_header_text:0 "Choose a New Destiny"
 will_become_adventurer:0 "Will become an [GetGovernment('landless_adventurer_government').GetName]"
 character_interest_breakdown_header:0 "Interesting Aspects"
 different_government_desc:0 "Has a Different Government"
 opposite_struggle_faction_desc:0 "Opposite Faction in a Struggle"
