l_english:
 MESSAGE_SETTINGS_WINDOW_NAME:0 "Message Settings"
 MESSAGE_SETTINGS_WINDOW_TT:0 "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nEdit Message frequency and visibility by filtered groups."
 MESSAGE_SETTINGS_WINDOW_RESET:0 "Reset to Default"
 MESSAGE_SETTINGS_WINDOW_RESET_TT:0 "#T Reset Message Settings#!\n#I Click to reset current changes to Default Settings#!"
 MESSAGE_SETTINGS_WINDOW_APPLY:0 "Apply Changes"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT:0 "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Click to close the Message Settings window and save current changes#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED:0 "@check_icon! Feed"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST:0 "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP:0 "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN:0 "@cross_icon! Never"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE:0 "Filter Group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT:0 "Name of the message filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE:0 "Appearance"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT:0 "How to display messages of this filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE:0 "Pause"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT:0 "If game should pause when messages of this filter appear"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT:0 "#T Toggle Auto-Pause#!\n#I Toggle to pause the game when messages of this filter appear#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP:0 "#T Dismiss Message#!\n#I Click to dismiss the current message and show the next message in the queue#!"
