l_english:
 MESSAGE_SETTINGS_WINDOW_NAME:0 "Ustawienia wiadomości"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT:0 "#I Kliknij, aby otworzyć ustawienia wiadomości#!"
 MESSAGE_SETTINGS_WINDOW_TT:0 "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nEdit Message frequency and visibility by filtered groups."
 MESSAGE_SETTINGS_WINDOW_RESET:0 "Przywróć domyślne"
 MESSAGE_SETTINGS_WINDOW_RESET_TT:0 "#T Reset Message Settings#!\n#I Click to reset current changes to Default Settings#!"
 MESSAGE_SETTINGS_WINDOW_APPLY:0 "Zatwierdź zmiany"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT:0 "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Click to close the Message Settings window and save current changes#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED:0 "@check_icon! Feed"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST:0 "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP:0 "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN:0 "@cross_icon! Never"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER:0 "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE:0 "Filter Group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT:0 "Name of the message filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE:0 "Appearance"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT:0 "How to display messages of this filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE:0 "Pause"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT:0 "If game should pause when messages of this filter appear"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT:0 "#T Toggle Auto-Pause#!\n#I Toggle to pause the game when messages of this filter appear#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP:0 "#T Dismiss Message#!\n#I Click to dismiss the current message and show the next message in the queue#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE:0 "Custom Message"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT:0 "#T Custom Message#!\n#I Click to write a custom message to yourself and select when you want to receive it#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE:0 "Arrival Date: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE:0 "Title:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC:0 "Description:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD:0 "Discard"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT:0 "#T Discard Message#!\n#I Click to discard current message#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND:0 "Send"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT:0 "#T Send#!\n#I Click to send current message#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY:0 "Dzień"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH:0 "Miesiąc"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR:0 "Rok"
